# Spring properties
spring:
  application:
     name: service  # Service registers under this name


# Map the error path to error template (for Thymeleaf)
error:
  path: /error

# HTTP Server
server:
  port: 7001   # HTTP (Tomcat) port
#  port: 2222


